package com.urva.myfinance.coinTrack.broker.core.session;

/**
 * Angel One SmartAPI direct-login credentials.
 *
 * Unlike Zerodha / Upstox there is no OAuth redirect — the backend logs in directly
 * with clientCode + password + a live TOTP code generated from a stored TOTP seed.
 *
 * @param apiKey             SmartAPI API key (sent in X-PrivateKey header).
 * @param clientCode         Angel One login ID (plaintext).
 * @param encryptedPassword  Trading PIN / MPIN, AES-256-GCM encrypted (decrypted in adapter).
 * @param totp               Live 6-digit TOTP code (generated by the adapter from the stored seed).
 */
public record AngelOneCredentials(
    String apiKey,
    String clientCode,
    String encryptedPassword,
    String totp
) implements BrokerCredentials {}
