epf.interest-rates[0].financialYear=2016-2017
epf.interest-rates[0].ratePercent=8.65
epf.interest-rates[0].effectiveDate=2016-04-01

epf.interest-rates[1].financialYear=2017-2018
epf.interest-rates[1].ratePercent=8.55
epf.interest-rates[1].effectiveDate=2017-04-01

epf.interest-rates[2].financialYear=2018-2019
epf.interest-rates[2].ratePercent=8.65
epf.interest-rates[2].effectiveDate=2018-04-01

epf.interest-rates[3].financialYear=2019-2020
epf.interest-rates[3].ratePercent=8.50
epf.interest-rates[3].effectiveDate=2019-04-01

epf.interest-rates[4].financialYear=2020-2021
epf.interest-rates[4].ratePercent=8.50
epf.interest-rates[4].effectiveDate=2020-04-01

epf.interest-rates[5].financialYear=2021-2022
epf.interest-rates[5].ratePercent=8.10
epf.interest-rates[5].effectiveDate=2021-04-01

epf.interest-rates[6].financialYear=2022-2023
epf.interest-rates[6].ratePercent=8.15
epf.interest-rates[6].effectiveDate=2022-04-01

epf.interest-rates[7].financialYear=2023-2024
epf.interest-rates[7].ratePercent=8.25
epf.interest-rates[7].effectiveDate=2023-04-01

epf.interest-rates[8].financialYear=2024-2025
epf.interest-rates[8].ratePercent=8.25
epf.interest-rates[8].effectiveDate=2024-04-01

epf.interest-rates[9].financialYear=2025-2026
epf.interest-rates[9].ratePercent=8.25
epf.interest-rates[9].effectiveDate=2025-04-01