# Stamp duty introduced on July 1, 2020 at 0.005%
mf.charges.stamp-duties[0].ratePercent=0.000
mf.charges.stamp-duties[0].effectiveDate=2000-01-01

mf.charges.stamp-duties[1].ratePercent=0.005
mf.charges.stamp-duties[1].effectiveDate=2020-07-01

# STT rate for Equity-oriented mutual funds is 0.001%
mf.charges.stt-rates[0].ratePercent=0.001
mf.charges.stt-rates[0].effectiveDate=2000-01-01
