export const SEBI_MF_CATEGORIES = [
  {
    group: "Equity Funds",
    categories: [
      "Large Cap",
      "Large & Mid Cap",
      "Mid Cap",
      "Small Cap",
      "Multi Cap",
      "Flexi Cap",
      "Focused",
      "Value",
      "Contra",
      "Dividend Yield",
      "ELSS",
      "Sectoral",
      "Thematic",
    ],
  },
  {
    group: "Debt Funds",
    categories: [
      "Overnight",
      "Liquid",
      "Ultra Short Duration",
      "Low Duration",
      "Money Market",
      "Short Duration",
      "Medium Duration",
      "Medium to Long Duration",
      "Long Duration",
      "Dynamic Bond",
      "Corporate Bond",
      "Credit Risk",
      "Banking & PSU",
      "Gilt",
      "Gilt 10 Year",
      "Floater",
    ],
  },
  {
    group: "Hybrid Funds",
    categories: [
      "Conservative Hybrid",
      "Balanced Hybrid",
      "Aggressive Hybrid",
      "Balanced Advantage",
      "Multi Asset Allocation",
      "Arbitrage",
      "Equity Savings",
    ],
  },
  {
    group: "Solution Oriented Funds",
    categories: [
      "Retirement",
      "Children",
    ],
  },
  {
    group: "Other & Passive Funds",
    categories: [
      "Index Fund",
      "ETF",
      "Fund of Funds",
      "Nifty 50 Index Fund",
      "Sensex Index Fund",
      "Gold ETF",
      "Silver ETF",
    ],
  },
];
